# Generated by Django 5.2.5 on 2025-08-17 08:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('ticket_type', models.CharField(choices=[('BUS', 'Bus'), ('PLANE', 'Plane'), ('TRAIN', 'Train'), ('FERRY', 'Ferry'), ('SUBWAY', 'Subway'), ('TRAM', 'Tram'), ('TAXI', 'Taxi'), ('SHUTTLE', 'Shuttle'), ('RIDE_SHARE', 'Ride Share'), ('MOVIE', 'Movie'), ('IMAX', 'IMAX Movie'), ('CINEMA_3D', '3D Cinema'), ('CINEMA_4DX', '4DX Cinema'), ('DRIVE_IN', 'Drive-in Movie'), ('SHORT_FILM', 'Short Film Screening'), ('DOCUMENTARY', 'Documentary Screening'), ('CONCERT', 'Concert'), ('MUSIC_FESTIVAL', 'Music Festival'), ('ART_EXHIBITION', 'Art Exhibition'), ('THEATER', 'Theater Play'), ('OPERA', 'Opera'), ('BALLET', 'Ballet'), ('STANDUP', 'Stand-up Comedy'), ('WORKSHOP', 'Workshop'), ('CONFERENCE', 'Conference'), ('SEMINAR', 'Seminar'), ('MEETUP', 'Meetup Event'), ('SPORT_MATCH', 'Sport Match'), ('TOURNAMENT', 'Tournament'), ('AMUSEMENT_PARK', 'Amusement Park'), ('WATER_PARK', 'Water Park'), ('ZOO', 'Zoo'), ('AQUARIUM', 'Aquarium'), ('MUSEUM', 'Museum'), ('PLANETARIUM', 'Planetarium'), ('CINEMA_PASS', 'Cinema Pass'), ('CITY_TOUR', 'City Tour'), ('SIGHTSEEING', 'Sightseeing'), ('CRUISE', 'Cruise'), ('SAFARI', 'Safari'), ('HIKING', 'Hiking'), ('ADVENTURE_TRIP', 'Adventure Trip'), ('MOUNTAIN_EXPEDITION', 'Mountain Expedition'), ('ONLINE_COURSE', 'Online Course'), ('OFFLINE_COURSE', 'Offline Course'), ('TRAINING', 'Training'), ('CERTIFICATION', 'Certification Program'), ('TRADE_FAIR', 'Trade Fair'), ('FARMERS_MARKET', 'Farmers Market'), ('ART_CRAFT_FAIR', 'Art & Craft Fair'), ('BOOK_FAIR', 'Book Fair'), ('FOOD_FESTIVAL', 'Food Festival'), ('WINE_TASTING', 'Wine Tasting'), ('CHARITY_EVENT', 'Charity Event'), ('FUNDRAISER', 'Fundraiser'), ('AUCTION', 'Auction Event'), ('MARATHON', 'Marathon'), ('FUN_RUN', 'Fun Run'), ('CYCLING_EVENT', 'Cycling Event'), ('YOGA_CLASS', 'Yoga Class'), ('FITNESS_CLASS', 'Fitness Class'), ('BOOTCAMP', 'Bootcamp'), ('VIRTUAL_EVENT', 'Virtual Event'), ('ONLINE_WEBINAR', 'Webinar'), ('KIDS_ACTIVITY', 'Kids Activity'), ('FAMILY_EVENT', 'Family Event'), ('PET_SHOW', 'Pet Show'), ('FASHION_SHOW', 'Fashion Show'), ('COMEDY_SHOW', 'Comedy Show'), ('GAMING_EVENT', 'Gaming Event'), ('ESPORTS', 'Esports Tournament'), ('CARNIVAL', 'Carnival'), ('PARADE', 'Parade'), ('WORKSHOP_KIDS', 'Kids Workshop'), ('TALK_SHOW', 'Talk Show'), ('CULTURAL_EVENT', 'Cultural Event'), ('HISTORICAL_TOUR', 'Historical Tour'), ('CRUISE_DINNER', 'Cruise Dinner'), ('FOOD_COOKING_CLASS', 'Cooking Class'), ('PHOTO_EXHIBITION', 'Photo Exhibition'), ('FILM_FESTIVAL', 'Film Festival'), ('BOAT_RIDE', 'Boat Ride'), ('HELICOPTER_RIDE', 'Helicopter Ride'), ('HOT_AIR_BALLOON', 'Hot Air Balloon Ride'), ('SCUBA_DIVING', 'Scuba Diving'), ('SKYDIVING', 'Skydiving'), ('PARAGLIDING', 'Paragliding'), ('WINTER_SPORTS', 'Winter Sports'), ('SKIING', 'Skiing'), ('SNOWBOARDING', 'Snowboarding'), ('CAMPING', 'Camping'), ('SURFING', 'Surfing'), ('MUSIC_CLASS', 'Music Class'), ('DANCE_CLASS', 'Dance Class'), ('LANGUAGE_CLASS', 'Language Class'), ('ART_CLASS', 'Art Class'), ('PHOTOGRAPHY_CLASS', 'Photography Class'), ('HACKATHON', 'Hackathon'), ('TECH_TALK', 'Tech Talk'), ('STARTUP_EVENT', 'Startup Event'), ('BUSINESS_SEMINAR', 'Business Seminar'), ('CAREER_FAIR', 'Career Fair')], default='', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('bus_name', models.CharField(max_length=255)),
                ('bus_type', models.CharField(max_length=255)),
                ('departure', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('bus_number', models.CharField(max_length=255)),
                ('operator', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-issued_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['ticket_type'], name='tickets_bus_ticket__e17af5_idx'), models.Index(fields=['start_time'], name='tickets_bus_start_t_096da7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('is_booked', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
