# Generated by Django 5.2.5 on 2025-08-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedBusSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('date_of_journey', models.DateField()),
                ('results', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['from_city', 'to_city', 'date_of_journey'], name='tickets_cac_from_ci_2627c1_idx')],
            },
        ),
    ]
